### ISSUE TITLE
Doc site down?

### ISSUE THREAD

**Issue by gtod** [tfausak/purescript-neon#112]
Hey Taylor,

Thanks for writing Neon, I am just trying to read some of the docs but this link http://pursuit.purescript.org/packages/purescript-neon is giving a "Package not found" error.  I suppose I could take it up with the pursuit people but wanted to ask you first if it is by design or accident?

**Comment by tfausak** [comment]
It is by accident. Pursuit changed its documentation format which removed all existing pages. Neon's documentation is supposed to be generated automatically, but a separate issue prevents that. 

I will try to manually upload documentation soon. In the meantime, you can find the docs in the source on GitHub.

**Comment by tfausak** [comment]
This issue caused the Neon documentation to disappear: https://github.com/purescript/pursuit/issues/213

This issue prevents the automatic generation of the Neon documentation: https://github.com/purescript/purescript/issues/1880

**Comment by tfausak** [comment]
So the docs are gone because Pursuit dropped them in an upgrade. I could build them again, but that would require getting this library to build with the latest version of PureScript. The latest version is two major versions ahead of where Neon is now. I'm not really interested in bringing it up to speed because the amount of churn in the PureScript ecosystem is huge. I don't personally use it, so I'm not motivated to spend time keeping this up to date. Sorry!

**Comment by adius** [comment]
@gtod We released a new version yesterday and thereby reuploaded the docs as well. It now works with the latest version of PureScript again. :grin:
