### ISSUE TITLE
Using purescript in a pragmatic manner

### ISSUE THREAD

**Issue by katywings** [tfausak/purescript-neon#113]
Hey hey hey

I was really happy to see that someone had the same thoughts about the dozen imports with the official purescript way! Neon looks much more pragmatic and *realistic*! Is this still a thing? Are you using it for some projects? Are you planning to maintain this in the future? How was the community feedback? 😄

**Comment by tfausak** [comment]
I haven't really touched this in at least a year because I don't use PureScript for anything personally or professionally. Keeping up with PureScript's compiler and library ecosystem was too much given my situation. I am still interested in having a library like this, but I'm kind of waiting around for Purescript 1.0.0 before I put more energy into it. I'm not sure how the community at large felt about it. The Reddit community is pretty small and was ambivalent: https://www.reddit.com/r/purescript/comments/483ell/neon_an_alternative_purescript_prelude/

All that being said, there is one big technical problem with a library like this: I can't expect everyone to define instances for my weird type classes. Most stuff will have a [`Semigroup`](https://pursuit.purescript.org/packages/purescript-prelude/3.1.0/docs/Data.Semigroup#t:Semigroup) instance, for example, but hardly anything will have a [`HasAdd`](https://github.com/tfausak/purescript-neon/blob/f5d28b56d08bb5fa29665c61a53b853d160cabb0/src/Neon/Class/HasAdd.purs#L6) instance. I *think* instance chains (https://github.com/purescript/purescript/pull/2929) would allow me to provide a `HasAdd` instance if you have a `Semigroup` instance, but I'm not sure.

**Comment by LiamGoodacre** [comment]
@tfausak The functionality added in the "Instance chain groups" PR won't let you dispatch on whether or not a constraint is satisfied.

**Comment by katywings** [comment]
@tfausak Thx a lot for your detailled answer! I guess i just will give it some time and look how it evolves ;) I am actually not since long onto the fp programming train, so I cant really talk deeply about type classes and so on xD.

**Comment by tfausak** [comment]
@LiamGoodacre: Thanks! I figured that was the answer, but it's good to know for sure. 

@katywings: If you're looking for something to alleviate the import pain right now, check out Batteries. It's a collection of common PureScript libraries packaged together in a single module. (It's also probably out of date. Sorry!) https://github.com/tfausak/purescript-batteries

There may be other pragmatic PhreScript preludes out there. As I mentioned, I'm not really up to date with all things PureScript.

**Comment by katywings** [comment]
@tfausak Thanks for the tip with batteries! Currently i am reading a Dart book, but when I am back to PS I will maybe look at it :P

**Comment by adius** [comment]
@katywings  We just released a new version and thereby reuploaded the docs as well. It now works with the latest version of PureScript again. 😁

**Comment by katywings** [comment]
@adius Thanks a lot for keeping me up to date and your work :D

I hope I find soon time to give the Neon Purescript revolution a try!
